# SPDX-License-Identifier: PMPL-1.0-or-later
# Print Doctor (Presswerk engine) â€” Dioxus CLI Configuration

[application]
name = "presswerk"
default_platform = "desktop"

[application.asset_dir]
path = "assets"

[desktop]
title = "Print Doctor"

[mobile]
# iOS
[mobile.ios]
bundle_id = "org.hyperpolymath.printdoctor"
minimum_os_version = "16.0"
team_id = ""

# Android
[mobile.android]
package = "org.hyperpolymath.printdoctor"
min_sdk_version = 26
target_sdk_version = 34
